export type Locale = 'ru' | 'en';
export type Project = { id:string; title:Record<Locale,string>; summary:Record<Locale,string>; problem:Record<Locale,string>; solution:Record<Locale,string>; result:Record<Locale,string>; role:Record<Locale,string>; stack:string[]; accent:'pink'|'blue'|'yellow'|'green'|'red'|'violet'|'orange'; kind:string };

export const projects:Project[] = [
  { id:'content-factory', title:{ru:'Фабрика контента',en:'Content Factory'}, summary:{ru:'Одна идея превращается в посты, Shorts и AI-видео.',en:'One idea becomes posts, Shorts, and AI videos.'}, problem:{ru:'Придумывание форматов и ручной монтаж отнимали слишком много времени.',en:'Format ideation and manual editing consumed too much time.'}, solution:{ru:'Параллельный конвейер создаёт контент сразу для нескольких площадок.',en:'A parallel pipeline creates content for several platforms at once.'}, result:{ru:'Система экономит значительную часть ручного монтажа и поиска идей.',en:'The system removes a large share of manual editing and ideation work.'}, role:{ru:'Спроектировал и разработал систему целиком.',en:'Designed and built the complete system.'}, stack:['n8n','TypeScript','OpenAI API','Runway','YouTube API','Airtable','Supabase'], accent:'pink', kind:'IDEA → CONTENT' },
  { id:'mission-control', title:{ru:'Mission Control',en:'Mission Control'}, summary:{ru:'Система управления на основе Гермес.',en:'A control system built on Hermes.'}, problem:{ru:'Нужно было собрать управление системой в едином понятном пространстве.',en:'System controls needed a single, understandable workspace.'}, solution:{ru:'Единый центр управления связывает рабочие сценарии и состояния.',en:'A unified control center connects workflows and system states.'}, result:{ru:'Управление сложной системой стало собранным и обозримым.',en:'A complex system became easier to observe and operate.'}, role:{ru:'Программист проекта.',en:'Project engineer.'}, stack:['Agent Systems','Hermes'], accent:'violet', kind:'SYSTEM ONLINE' },
  { id:'savimpex', title:{ru:'Savimpex',en:'Savimpex'}, summary:{ru:'Логистическая система перевозок электроники и одежды.',en:'A logistics system for electronics and apparel transportation.'}, problem:{ru:'Перевозки разных категорий товаров требуют прозрачной координации.',en:'Transporting different goods requires transparent coordination.'}, solution:{ru:'Система собирает логистический процесс в один рабочий контур.',en:'The system brings the logistics process into one operational flow.'}, result:{ru:'Маршруты и перевозки становятся проще для контроля.',en:'Routes and shipments become easier to control.'}, role:{ru:'Разработчик системы.',en:'System developer.'}, stack:['Logistics','Web system'], accent:'blue', kind:'ROUTES / CARGO' },
  { id:'calibry-games', title:{ru:'Calibry Games',en:'Calibry Games'}, summary:{ru:'Игровое приложение с миографическими датчиками для людей с ограниченными возможностями.',en:'A myography-based gaming app for people with disabilities.'}, problem:{ru:'Обычные игровые способы ввода доступны не всем.',en:'Conventional game controls are not accessible to everyone.'}, solution:{ru:'Сигналы мышц с датчиков Calibry превращаются в игровые действия.',en:'Muscle signals from Calibry sensors become in-game actions.'}, result:{ru:'Игровой процесс получает альтернативный физический интерфейс.',en:'Gameplay gains an alternative physical interface.'}, role:{ru:'Разработчик приложения.',en:'Application developer.'}, stack:['Calibry','Myography','Accessibility'], accent:'green', kind:'HUMANS CAN PLAY' },
  { id:'moysklad-analytics', title:{ru:'Аналитика для «МойСклад»',en:'MoySklad Analytics'}, summary:{ru:'Плагин для анализа производительности продавцов.',en:'A plugin for analyzing sales-team performance.'}, problem:{ru:'Рабочие показатели продавцов сложно оценивать без отдельной аналитики.',en:'Sales performance is difficult to assess without focused analytics.'}, solution:{ru:'Плагин превращает данные «МойСклад» в понятный аналитический срез.',en:'The plugin turns MoySklad data into a clear analytical view.'}, result:{ru:'Руководитель быстрее видит результативность команды.',en:'Managers can understand team performance faster.'}, role:{ru:'Разработчик плагина.',en:'Plugin developer.'}, stack:['MoySklad','Analytics','Integration'], accent:'orange', kind:'SALES / SIGNALS' },
  { id:'mop-coins', title:{ru:'Кликер МОП-коинов',en:'MOP Coins Clicker'}, summary:{ru:'Игра-кликер с использованием криптовалюты.',en:'A clicker game with cryptocurrency mechanics.'}, problem:{ru:'Хотелось проверить, как web3-механика работает внутри простой игровой петли.',en:'The experiment tested web3 mechanics inside a simple game loop.'}, solution:{ru:'Кликер соединяет понятный игровой цикл с криптовалютной частью.',en:'The clicker connects a familiar game loop with a crypto layer.'}, result:{ru:'Получился работающий игровой web3-эксперимент.',en:'The result is a working web3 game experiment.'}, role:{ru:'Разработчик игры.',en:'Game developer.'}, stack:['Solidity','Web3','Game loop'], accent:'yellow', kind:'CLICK / EARN' },
  { id:'visual-novel', title:{ru:'Визуальная новелла',en:'Visual Novel'}, summary:{ru:'Законченная история примерно на два часа игры.',en:'A complete story with roughly two hours of playtime.'}, problem:{ru:'Нужно было удержать темп истории и собрать целостный игровой опыт.',en:'The challenge was to sustain story pacing and create a cohesive experience.'}, solution:{ru:'Сюжет, интерфейс и игровые состояния собраны в единый сценарий.',en:'Story, interface, and game states were assembled into one flow.'}, result:{ru:'Готовая визуальная новелла продолжительностью около двух часов.',en:'A finished visual novel with around two hours of gameplay.'}, role:{ru:'Разработчик проекта.',en:'Project developer.'}, stack:['Narrative','Game UI','JavaScript'], accent:'red', kind:'2 HOURS / STORY' },
];

export const copy = {
  ru:{role:'Инженер AI-продуктов',open:'открыть записную книжку ↓',tabs:['ОБО МНЕ','ПРОЕКТЫ','СКИЛЛЫ','СВЯЗЬ'],aboutTitle:['Привет, я Илья.','Строю странные','полезные штуки.'],about:'Мне 21. Я инженер и программист. Люблю брать сложные идеи и превращать их в системы, которыми уже можно пользоваться.',facts:['1,5 года практики','Инженерная академия ЮФУ','Agent Systems · RAG · n8n'],projectsTitle:'Что я уже собрал',projectsIntro:'Семь проектов из разных миров. Нажми на наклейку — откроется полный лист дела.',caseLabels:['задача','что я сделал','результат','моя роль'],ask:'спросить о проекте →',skillsTitle:'Чем я думаю',processTitle:'Как я работаю',process:['разобраться','собрать прототип','проверить','довести до системы'],contactTitle:'Есть странная идея?',contactText:'Если у вас есть сложный процесс или продуктовая гипотеза — давайте превратим её в работающую систему.',telegram:'Написать в Telegram',email:'Отправить email',call:'Договориться о созвоне в Telegram'},
  en:{role:'AI & Product Engineer',open:'open the notebook ↓',tabs:['ABOUT','PROJECTS','SKILLS','CONTACT'],aboutTitle:['Hi, I’m Ilya.','I build strange,','useful things.'],about:'I’m 21, an engineer and programmer. I like taking difficult ideas and turning them into systems people can actually use.',facts:['1.5 years in practice','SFedU Engineering Academy','Agent Systems · RAG · n8n'],projectsTitle:'Things I have built',projectsIntro:'Seven projects from different worlds. Click a sticker to open the full case sheet.',caseLabels:['problem','what I built','result','my role'],ask:'ask me about this project →',skillsTitle:'Tools I think with',processTitle:'How I work',process:['understand','prototype','test','ship the system'],contactTitle:'Have a strange idea?',contactText:'If you have a complex process or a product hypothesis, let’s turn it into a working system.',telegram:'Message on Telegram',email:'Send an email',call:'Arrange a call in Telegram'},
} as const;
